[build]
  publish = "public" # The directory for your static assets (HTML, CSS, JS)
  functions = "netlify/functions" # Directory for Netlify Functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
